Feat/donation
commons-stack/tech-dapp pull request #197
Opened 2021-03-09 19:59 UTC by MerlinEgalite

2021-03-09 21:54 UTC, tamarandom commented
More info please. ;)

2021-03-10 13:31 UTC, mendesfabio requested changes

2021-03-10 13:31 UTC, mendesfabio commented on src/pages/contribute/components/Contribute.js
> +    if (balance > 1125) setHasPaidDues(true);
I don't think we should use the CSTK balance to check if dues were paid. Instead of that, we have the `effectiveBalance`, which represents the amount of DAI contributed.

2021-03-10 13:31 UTC, mendesfabio commented on src/pages/contribute/components/Contribute.js
> +    if (balance > 1125) setHasPaidDues(true);
At line 152 we have the following code: `{effectiveBalance > 0 ? cstkBalance : '0'} CSTK`. Basically, I did this to only show the CSTK score if the user paid the dues. You may ask me, shouldn't it be `effectiveBalance >= 450`? Actually, yes, but we had some issues, Griff can explain you better.

2021-03-10 19:42 UTC, merged